Repository RGB-WG/rgb-node, pull requests merged in 2020-10, with the labels that each got.

#77 Updating to the latest LNP/BP Core Library & extensions implementation
  Cargo.lock
  Cargo.toml
  ffi/Cargo.toml
  ffi/src/lib.rs
  src/api/reply.rs
  src/bin/fungibled.rs
  src/bin/rgb-cli.rs
  src/bin/rgbd.rs
  src/bin/stashd.rs
  src/cli/config.rs
  src/cli/fungible.rs
  src/contracts/fungible/cache/file.rs
  src/contracts/fungible/config.rs
  src/contracts/fungible/data/asset.rs
  src/contracts/fungible/data/schema.rs
  src/contracts/fungible/processor.rs
  src/contracts/fungible/runtime.rs
  src/i9n/config.rs
  src/i9n/fungible.rs
  src/i9n/runtime.rs
  src/lib.rs
  src/rgbd/config.rs
  src/rgbd/runtime.rs
  src/stash/config.rs
  src/stash/runtime.rs
  src/stash/stash.rs
  src/stash/storage/disk.rs
  src/stash/storage/store.rs
  src/util/file.rs
  src/util/magic_numbers.rs
Labels: enhancement

#19 RGB: Fungible assets update: burn, replacement, renomination
  Cargo.lock
  Cargo.toml
  ffi/ios/DemoApp/RGB Demo App.xcodeproj/project.pbxproj
  ffi/src/lib.rs
  src/api/fungible.rs
  src/contracts/fungible/data/asset.rs
  src/contracts/fungible/data/schema.rs
  src/contracts/fungible/processor.rs
  src/contracts/fungible/runtime.rs
  src/i9n/fungible.rs
  src/util/macros.rs
Labels: *security*, feature

#80 RGB-20: Inflation improvements
  Cargo.lock
  src/contracts/fungible/data/asset.rs
  src/contracts/fungible/data/schema.rs
  src/contracts/fungible/processor.rs
Labels: enhancement

#89 [WIP] Sqlite Database engine for asset cache
  Cargo.toml
  db/cache/diesel.toml
  db/cache/migrations/00000000000000_diesel_initial_setup/down.sql
  db/cache/migrations/00000000000000_diesel_initial_setup/up.sql
  db/cache/migrations/2020-03-21-151310_base/down.sql
  db/cache/migrations/2020-03-21-151310_base/up.sql
  src/contracts/fungible/cache/cache.rs
  src/contracts/fungible/cache/file.rs
  src/contracts/fungible/cache/mod.rs
  src/contracts/fungible/cache/models.rs
  src/contracts/fungible/cache/schema.rs
  src/contracts/fungible/cache/sql.rs
  src/contracts/fungible/data/asset.rs
  src/contracts/fungible/mod.rs
  src/error.rs
  src/lib.rs
  test/test_db.sh
Labels: feature

#90 Release v0.1
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .rustfmt.toml
  .travis.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Cargo.toml
  Dockerfile
  README.md
  codecov.yml
  rust-toolchain
  src/api/fungible.rs
  src/api/reply.rs
  src/cli/config.rs
  src/cli/fungible.rs
  src/cli/runtime.rs
  src/cli/stash.rs
  src/constants.rs
  src/contracts/collectible/data/schema.rs
  src/contracts/fungible/cache/cache.rs
  src/contracts/fungible/cache/models.rs
  src/contracts/fungible/cache/sql.rs
  src/contracts/fungible/config.rs
  src/contracts/fungible/data/asset.rs
  src/contracts/fungible/data/invoice.rs
  src/contracts/fungible/data/mod.rs
  src/contracts/fungible/data/outcoins.rs
  src/contracts/fungible/data/schema.rs
  src/contracts/fungible/mod.rs
  src/contracts/fungible/processor.rs
  src/contracts/fungible/runtime.rs
  src/error.rs
  src/i9n/fungible.rs
  src/lib.rs
  src/rgbd/config.rs
  src/rgbd/runtime.rs
  src/service.rs
  src/stash/config.rs
  src/stash/electrum.rs
  src/stash/index/btree.rs
  src/stash/index/index.rs
  src/stash/runtime.rs
  src/stash/stash.rs
  src/stash/storage/disk.rs
  src/stash/storage/store.rs
  src/util/file.rs
  src/util/seal_spec.rs
  test/info.md
  test/invoice.txt
Labels: epic

#91 Cache API enhancement
  src/contracts/fungible/cache/cache.rs
  src/contracts/fungible/cache/file.rs
  src/contracts/fungible/cache/sql.rs
  test/test_db.sh
Labels: feature

#93 Expose rgb::fungible::data::invoice::Error as InvoiceError
  src/contracts/fungible/data/mod.rs
  src/contracts/fungible/mod.rs
Labels: enhancement
