Repository RGB-WG/rgb-node, pull requests merged in 2020-12, with the labels that each got.

#113 README: add missing dependency 'libsqlite3-dev'
  README.md
Labels: ci

#114 Update README.md
  README.md
Labels: documentation

#104 add demo of rgb-node:0.1
  README.md
  doc/demo-0.1/Dockerfile
  doc/demo-0.1/README.md
  doc/demo-0.1/docker-compose.yml
  doc/demo-0.1/samples/source_tx.psbt
Labels: documentation

#115 Hammersbald storage Implementation for stash
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/stash/storage/disk.rs
  src/stash/storage/hammersbald.rs
  src/stash/storage/mod.rs
  src/stash/storage/store.rs
Labels: feature

#22 RGB: audit log schema proposal
  src/contracts/auditlog/data/schema.rs
Labels: enhancement

#21 RGB: identity schema proposal
  src/contracts/identity/data/schema.rs
Labels: enhancement

#120 I9n/import list
  src/contracts/fungible/data/invoice.rs
  src/contracts/fungible/runtime.rs
  src/i9n/fungible.rs
Labels: *compatibility*

#123 README: fix build command
  README.md
Labels: ci
