Repository RGB-WG/rgb-node, pull requests merged in 2020-11, with the labels that each got.

#99 Add accept and validate methods in i9n
  src/i9n/fungible.rs
Labels: *compatibility*

#100 Add asset_allocations and outpoint_assets in i9n
  src/i9n/fungible.rs
Labels: *compatibility*

#105 i9n: fix outpoint_assets and asset_allocations responses
  .github/workflows/build.yml
  src/i9n/fungible.rs
Labels: bug

#98 CI: add crate publication workflow
  .github/workflows/publication.yml
Labels: ci

#110 Fix ignored config params
  src/contracts/fungible/config.rs
  src/i9n/config.rs
  src/i9n/runtime.rs
  src/rgbd/config.rs
  src/rgbd/runtime.rs
  src/stash/config.rs
Labels: bug

#112 Fixing serde dependency in default builds
  Cargo.lock
  Cargo.toml
  src/api/fungible.rs
  src/contracts/fungible/cache/cache.rs
  src/contracts/fungible/cache/file.rs
  src/contracts/fungible/config.rs
  src/contracts/fungible/data/asset.rs
  src/contracts/fungible/data/outcoins.rs
  src/contracts/fungible/processor.rs
  src/lib.rs
  src/rgbd/config.rs
  src/util/seal_spec.rs
Labels: ci
