Repository RGB-WG/rgb-node, pull requests merged in 2021-03, with the labels that each got.

#138 Consignment conceal procedure
  Cargo.lock
  src/cli/fungible.rs
  src/stashd/stash.rs
  src/util/file.rs
Labels: *privacy*, enhancement

#139 Fix asset 'fractional_bits' error
  Cargo.lock
  src/fungibled/sql/models.rs
Labels: bug

#140 Fix filename extension of consignment files
  src/cli/fungible.rs
Labels: bug

#147 Self-accepting consignment with no blinding: closes #146
  src/cli/fungible.rs
Labels: enhancement

#148 Transfering from multi-asset outputs: closes #143
  Cargo.lock
  src/cli/fungible.rs
  src/cli/runtime.rs
  src/fungibled/runtime.rs
  src/i9n/fungible.rs
  src/rpc/fungible.rs
  src/rpc/reply.rs
  src/rpc/stash.rs
  src/stashd/runtime.rs
  src/stashd/stash.rs
  src/util/file.rs
  src/util/magic_numbers.rs
Labels: *security*, epic

#149 Merge-revealed procedure for consignments
  src/stashd/stash.rs
Labels: *privacy*, *security*, bug, enhancement

#150 rgb-node demo updated as per v0.4.0
  doc/demo-0.1/README.md
  doc/demo-0.1/docker-compose.yml
  sample/consignment.rgb
  sample/disclosure.rgb
  sample/witness.psbt
Labels: documentation
